#!/usr/bin/env bash

set -o pipefail
set -eu

source $(dirname $BASH_SOURCE)/../../vendor/heroku/heroku-buildpack-php/support/build/_util/include/manifest.sh

OUT_PREFIX=$1

export PATH=${OUT_PREFIX}/bin:${PATH}

series=$(php-config --version | cut -d. -f1,2)
php_ext_dir=$(php-config --extension-dir)

dep_name=relay
dep_formula=${0#$WORKSPACE_DIR/}
dep_version=${dep_formula##*"/${dep_name}-"}
dep_package=ext-${dep_name}-${dep_version}
dep_dirname=relay-v${dep_version}-php${series}-debian-x86-64
dep_archive_name=${dep_dirname}.tar.gz
dep_url=https://cachewerk.s3.amazonaws.com/relay/v${dep_version}/${dep_archive_name}
dep_manifest=${dep_package}_php-${series}.composer.json

echo "-----> Building ${dep_package}..."

curl -L ${dep_url} | tar xz

pushd ${dep_dirname}
rm -rf ${OUT_PREFIX}/*
uuid=$(cat /proc/sys/kernel/random/uuid)
sed -i "s/31415926-5358-9793-2384-626433832795/${uuid}/" relay-static.so
mkdir -p ${php_ext_dir}
mv relay-static.so ${php_ext_dir}/relay.so
popd

MANIFEST_REQUIRE="${MANIFEST_REQUIRE:-"{\"heroku-sys/php\":\"${series}.*\"}"}"
MANIFEST_CONFLICT="${MANIFEST_CONFLICT:-"{}"}"
MANIFEST_REPLACE="${MANIFEST_REPLACE:-"{}"}"
MANIFEST_PROVIDE="${MANIFEST_PROVIDE:-"{}"}"
MANIFEST_EXTRA="${MANIFEST_EXTRA:-"{}"}"

python $(dirname $BASH_SOURCE)/../../vendor/heroku/heroku-buildpack-php/support/build/_util/include/manifest.py "heroku-sys-php-extension" "heroku-sys/ext-${dep_name}" "$dep_version" "${dep_formula}.tar.gz" "$MANIFEST_REQUIRE" "$MANIFEST_CONFLICT" "$MANIFEST_REPLACE" "$MANIFEST_PROVIDE" "$MANIFEST_EXTRA" > $dep_manifest

print_or_export_manifest_cmd "$(generate_manifest_cmd "$dep_manifest")"
