#!/usr/bin/env bash

set -o pipefail
set -eu

source $(dirname $BASH_SOURCE)/../vendor/heroku/heroku-buildpack-php/support/build/util/include/manifest.sh

OUT_PREFIX=$1

export PATH=${OUT_PREFIX}/bin:${PATH}

series=$(php-config --version | cut -d. -f1,2)
php_ext_dir=$(php-config --extension-dir)

dep_name=ext-relay
dep_package=${0#"${WORKSPACE_DIR}/"} # trim WORKSPACE_DIR prefix from $0 (the invoked package recipe)
dep_formula=${dep_package} # trim "_php-x.y" suffix from package name to get formula name
dep_build=${dep_package#"${dep_name}-"} # strip formula name from front of full package name
dep_build=${dep_build%"_php-${series}"} # strip "_php-x.y" suffix from end
dep_version=${dep_build%%"+"*} # strip build metadata off the end of the version
dep_variant=$(if openssl version | grep -q "OpenSSL 3"; then echo "+libssl3"; else echo ""; fi)
dep_dirname=relay-v${dep_version}-php${series}-debian-x86-64${dep_variant}
dep_archive_name=${dep_dirname}.tar.gz
dep_url=https://builds.r2.relay.so/v${dep_version}/${dep_archive_name}
dep_manifest=${dep_package}_php-${series}.composer.json

echo "-----> Building ${dep_name} (${dep_version}, for PHP ${series}) ..."

curl -L ${dep_url} | tar xz

pushd ${dep_dirname}
rm -rf ${OUT_PREFIX}/*

mv relay-pkg.so relay.so
chmod 700 relay.so

uuid=$(cat /proc/sys/kernel/random/uuid)
sed -i "s/00000000-0000-0000-0000-000000000000/${uuid}/" relay.so

mkdir -p ${php_ext_dir}
cp relay.so ${php_ext_dir}

mkdir -p ${OUT_PREFIX}/etc/php/conf.d
cp relay.ini ${OUT_PREFIX}/etc/php/conf.d/relay.ini-dist
popd

MANIFEST_REQUIRE="${MANIFEST_REQUIRE:-"{\"heroku-sys/php\":\"${series}.*\",\"heroku-sys/liblzf\":\"*\",\"heroku-sys/lz4\":\"*\",\"heroku-sys/zstd\":\"*\",\"heroku-sys/ext-json\":\"*\",\"heroku-sys/ext-igbinary\":\"*\",\"heroku-sys/ext-msgpack\":\"*\"}"}"
MANIFEST_CONFLICT="${MANIFEST_CONFLICT:-"{}"}"
MANIFEST_REPLACE="${MANIFEST_REPLACE:-"{}"}"
MANIFEST_PROVIDE="${MANIFEST_PROVIDE:-"{}"}"
MANIFEST_EXTRA="${MANIFEST_EXTRA:-"{\"config\":\"etc/php/conf.d/relay.ini-dist\"}"}"

python $(dirname $BASH_SOURCE)/../vendor/heroku/heroku-buildpack-php/support/build/util/include/manifest.py "heroku-sys-php-extension" "heroku-sys/${dep_name}" "$dep_version" "${dep_formula}.tar.gz" "$MANIFEST_REQUIRE" "$MANIFEST_CONFLICT" "$MANIFEST_REPLACE" "$MANIFEST_PROVIDE" "$MANIFEST_EXTRA" > $dep_manifest

print_or_export_manifest_cmd "$(generate_manifest_cmd "$dep_manifest")"
