#!/usr/bin/env bash

dep_name=ext-swoole

CONFIGURE_EXTRA="--enable-swoole-json --enable-swoole-curl --enable-http2 --enable-sockets --enable-mysqlnd --enable-openssl"

source $(dirname $BASH_SOURCE)/../vendor/heroku/heroku-buildpack-php/support/build/formulae/include/pecl-ext
