
    </main>

    <footer class="bg-white">
      <div class="max-w-2xl mx-auto py-12 px-4 overflow-hidden sm:px-6 lg:px-8">
        <nav class="-mx-5 -my-2 flex flex-wrap justify-center" aria-label="Footer">
          <div class="px-5 py-2">
            <a href="https://github.com/cachewerk/heroku-php-extensions" class="text-base text-gray-500 hover:text-indigo-600">
              GitHub
            </a>
          </div>
          <div class="px-5 py-2">
            <a href="https://s3.us-east-1.amazonaws.com/heroku-php-extensions/index.html" class="text-base text-gray-500 hover:text-indigo-600">
              S3 Bucket
            </a>
          </div>
        </nav>
      </div>
    </footer>

  </body>
</html>
