<!doctype html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Heroku PHP Extensions</title>
    <link
      rel="stylesheet"
      href="https://cdnjs.cloudflare.com/ajax/libs/tailwindcss/2.0.3/tailwind.min.css"
      integrity="sha512-wl80ucxCRpLkfaCnbM88y4AxnutbGk327762eM9E/rRTvY/ZGAHWMZrYUq66VQBYMIYDFpDdJAOGSLyIPHZ2IQ=="
      crossorigin="anonymous" />
  </head>
  <body class="bg-white antialiased">

    <header class="max-w-4xl mx-auto">
      <div class="py-16 px-4 sm:py-24 sm:px-6 lg:px-8">
        <div class="text-center">
          <h1 class="text-base font-semibold text-indigo-600 tracking-wide uppercase">
            CacheWerk
          </h1>
          <h1 class="mt-1 text-4xl font-extrabold text-gray-900 sm:text-5xl sm:tracking-tight lg:text-6xl">
            Heroku PHP Extensions
          </h2>
          <p class="max-w-xl mt-5 mx-auto text-xl text-gray-500">
            Pre-built PHP extensions for Heroku that are not included or fully supported by the official PHP buildpack.
          </p>
          <div class="mt-8 flex justify-center">
            <div class="inline-flex rounded-md shadow">
              <a href="https://github.com/cachewerk/heroku-php-extensions" class="inline-flex items-center justify-center px-5 py-3 border border-transparent text-base font-medium rounded-md text-white bg-indigo-600 hover:bg-indigo-700">
                GitHub repo
              </a>
            </div>
            <div class="ml-3 inline-flex">
              <a href="https://s3.us-east-1.amazonaws.com/heroku-php-extensions/index.html" class="inline-flex items-center justify-center px-5 py-3 border border-transparent text-base font-medium rounded-md text-indigo-700 bg-indigo-100 hover:bg-indigo-200">
                S3 bucket
              </a>
            </div>
          </div>
        </div>
      </div>
  </header>

  <main class="space-y-12">
